language: rust

include:
- os: linux
  sudo: required
  dist: trusty
  cache: apt
  before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libfuse-dev -qq
rust:
  - stable
  - beta
  - nightly 
