[package]
name = "blitz-archiving-explorer"
version = "0.1.0"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>"]

[dependencies]
flate2 = "1.0"
tar = "0.4"
sled = "0.21"
serde = "1.0"
serde_json = "1.0"
notify = "4.0"
log = "0.4"
simplelog = "0.5"
fuse = "0.3"
libc = "0.2"
time = "0.1"
